name: Fegg

on:
  workflow_dispatch:
  push:
  schedule:
        - cron: "0 */6 * * *" 
# runs on the 0th minute, every 6 hours (0,6,12,18), every day of month, every month, every day of week 
# because github actions jobs are limited to 6 hours

concurrency: 
  group: ${{ github.workflow }}-${{ github.fegg }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py==1.7.3
        pip install yt_dlp
        pip install discord-py-slash-command==3.0.3
    - name: execute py script
      env: 
          TOKEN: ${{ secrets.TOKEN }}
      run: |
        python main.py
