name: Fegg

on:
  workflow_dispatch:
  # push:
  # schedule:
  #       - cron: "0 0 * * *" #runs at 00:00 UTC everyday

concurrency: 
  group: ${{ github.workflow }}-${{ github.fegg }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py
        pip install yt_dlp
        pip install discord-py-slash-command
    - name: execute py script
      env: 
          TOKEN: ${{ secrets.TOKEN }}
      run: |
        python main.py
